config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get 'restaurants', to: 'restaurants#index'
  get 'restaurants/:restaurant_id/reviews/new', to: 'reviews#new', as: :new_restaurant_review
  post 'restaurants/:restaurant_id/reviews', to: 'reviews#create', as: :restaurant_reviews
  get 'restaurants/new', to: 'restaurants#new'
  post 'restaurants', to: 'restaurants#create'
  get 'restaurants/:id', to: 'restaurants#show', as: :restaurant
  # resources :restaurants, only: [:index, :new, :create, :show] do
  #   resources :reviews, only: [:new, :create]
  # end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  CATEGORY = ["chinese", "italian", "japanese", "french", "belgian"]
  has_many :reviews, dependent: :destroy

  validates :name, :address, :category, presence: true
  validates :category, inclusion: { in: CATEGORY }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, numericality: { only_integer: true }
  validates :rating, numericality: { in: 0..5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show]

  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<div class="container">
  <h1>Restaurants</h1>

    <%= link_to "create new Restaurant", restaurants_new_path(@restaurant), class:"btn btn-primary" %>

    <ul>
      <% @restaurants.each do |restaurant| %>
        <li><%=link_to restaurant.name, restaurant_path(restaurant) %></li>
      <% end %>
    </ul>
</div>

app/views/restaurants/new.html.erb
<div class="container">
  <%= simple_form_for(@restaurant) do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :category, collection: Restaurant::CATEGORY %>
    <%= f.submit class:"btn btn-primary" %>
  <% end %>
    <br>
  <%= link_to "back to Resturants", restaurants_path, class:"btn btn-primary"  %>
</div>

app/views/restaurants/show.html.erb
<div class="container">
  <h2><%= @restaurant.name %></h2>
  <p><%= @restaurant.address %></p>
  <p><%= @restaurant.category %></p>

  <%= link_to "create review", new_restaurant_review_path(@restaurant), class:"btn btn-primary"  %>
  <%= link_to "back to Restaurants", restaurants_path, class:"btn btn-primary"  %>

  <p><strong>Reviews</strong></p>
  <ul class="list-group">
    <% @restaurant.reviews.each do |review| %>
      <li class="list-group-item"><%= review.content %> <%= review.rating %></li>
    <% end %>
  </ul>
  <br>
</div>

app/views/reviews/new.html.erb
<h1>New review</h1>
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>